version: '3'

services:
  bing-wallpaper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bing-wallpaper
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./cache:/app/cache
      - ./config:/app/config
    environment:
      - TZ=Asia/Shanghai
      - BING_API_SERVER_PORT=3000
      - BING_API_SERVER_HOST=0.0.0.0
      - BING_API_STORAGE_LOCAL_PATH=/app/cache/images
      - BING_API_STORAGE_METADATAPATH=/app/cache/metadata.json
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
